### ISSUE TITLE
URL for downloading new weather data seems wrong

### ISSUE THREAD

**Issue by jcnesci** [cambecc/earth#79]
While trying to use grib2json to get new weather data from NOMADS, I noticed that the URL format shown in the README here (and in the grib2json repo's README) doesn't load.

For example, this URL
```http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs.pl?file=gfs.t00z.pgrb2.1p00.f000&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&dir=%2Fgfs.${20140101}00```
produces a 404 page that says: "Not Found: The requested URL /cgi-bin/filter_gfs.pl was not found on this server."

While I try to figure out how the NOMADS file serving format has changed, I figured I'd let people know here, and if someone already knows the new format then they can provide it.

**Comment by mschreib28** [comment]
Is this what you're looking for?

http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl

**Comment by polyestersuede** [comment]
This is the command you'll need:

`curl "http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl?file=gfs.t00z.pgrb2.1p00.f000&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&dir=%2Fgfs.${YYYYMMDD}00" -o gfs.t00z.pgrb2.1p00.f000`

**Comment by michaelnarlock** [comment]
Hmmm...that command results in 404 for me.

**Comment by gustavost26** [comment]
> Este é o comando que você precisa:
> 
> `curl "http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl?file=gfs.t00z.pgrb2.1p00.f000&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&dir=%2Fgfs.${YYYYMMDD}00" -o gfs.t00z.pgrb2.1p00.f000`

I downloaded the following gfs.t00z.pgrb2.1p00.f000 config file shown in github.

But when executing the following command:
sh grib2json -d -n -o current-wind-surface-level-gfs-1.0.json gfs.t00z.pgrb2.1p00.f000

And presenting the following error:

java.io.IOException: java.io.IOException: Cant read gfs.t00z.pgrb2.1p00.f000: not a valid CDM file.
at ucar.nc2.NetcdfFile.open(NetcdfFile.java:425)
at ucar.nc2.NetcdfFile.open(NetcdfFile.java:392)
at ucar.nc2.NetcdfFile.open(NetcdfFile.java:379)
at ucar.nc2.NetcdfFile.open(NetcdfFile.java:367)
at net.nullschool.grib2json.Grib2Json.write(Grib2Json.java:114)
at net.nullschool.grib2json.Launcher.main(Launcher.java:75)
Caused by: java.io.IOException: Cant read gfs.t00z.pgrb2.1p00.f000: not a valid CDM file.
at ucar.nc2.NetcdfFile.open(NetcdfFile.java:803)
at ucar.nc2.NetcdfFile.open(NetcdfFile.java:422)
... 5 more

I noticed that the file I downloaded according to the github tutorial does not have the extension .grb2

How do I download a file with this extension for possible conversion to json?

Sources:
https://github.com/cambecc/earth
https://github.com/cambecc/grib2json

**Comment by gustavost26** [comment]
> > Este é o comando que você precisa:
> > `curl "http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl?file=gfs.t00z.pgrb2.1p00.f000&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&dir=%2Fgfs.${YYYYMMDD}00" -o gfs.t00z.pgrb2.1p00.f000`
> 
> I downloaded the following gfs.t00z.pgrb2.1p00.f000 config file shown in github.
> 
> But when executing the following command:
> sh grib2json -d -n -o current-wind-surface-level-gfs-1.0.json gfs.t00z.pgrb2.1p00.f000
> 
> And presenting the following error:
> 
> java.io.IOException: java.io.IOException: Cant read gfs.t00z.pgrb2.1p00.f000: not a valid CDM file.
> at ucar.nc2.NetcdfFile.open(NetcdfFile.java:425)
> at ucar.nc2.NetcdfFile.open(NetcdfFile.java:392)
> at ucar.nc2.NetcdfFile.open(NetcdfFile.java:379)
> at ucar.nc2.NetcdfFile.open(NetcdfFile.java:367)
> at net.nullschool.grib2json.Grib2Json.write(Grib2Json.java:114)
> at net.nullschool.grib2json.Launcher.main(Launcher.java:75)
> Caused by: java.io.IOException: Cant read gfs.t00z.pgrb2.1p00.f000: not a valid CDM file.
> at ucar.nc2.NetcdfFile.open(NetcdfFile.java:803)
> at ucar.nc2.NetcdfFile.open(NetcdfFile.java:422)
> ... 5 more
> 
> I noticed that the file I downloaded according to the github tutorial does not have the extension .grb2
> 
> How do I download a file with this extension for possible conversion to json?
> 
> Sources:
> https://github.com/cambecc/earth
> https://github.com/cambecc/grib2json

I downloaded the correct file to convert to json through this page: 
https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl
http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl?dir=%2Fgfs.2018122700
